### ISSUE TITLE
Not an issue but a question, hide when off

### ISSUE THREAD

**Issue by estradanet** [Snille/MMM-homeassistant-sensors#11]
Hi, this is not an issue but a question. I have a bunch of lights and I'd like to hide them when they are off, just to show when they are on.

Is this possible?

**Comment by Snille** [comment]
I missed your "issue" here, but did replay on the MM forum. Let me know if it worked out,

**Comment by Snille** [comment]
I have added "highDisplayThreshold" and "lowDisplayThreshold" for the sensors. So, you can now use this to only display the lights that are "lit" by using "power" as a threshold. :)

**Comment by estradanet** [comment]
Thank you very much!!!!! Yes I did post it here for your log. Thank you for your quick support :)

**Comment by estradanet** [comment]
Hi again, I thought I had it right. but not,

I tried highDisplayThreshold with a number (as it says it's a number, see below) but I can make it work, I tried from 0 to 100 (my lights are dimmable), even on and off and true or false but I could not make it work.

> | `highDisplayThreshold`   | `number` | You can specify a number, if the value/state of the sensor is higher then this the sensor will be shown in the table.|
> | `lowDisplayThreshold`    | `number` | You can specify a number, if the value/state of the sensor is lower then this the sensor will be shown in the table.|

highDisplayThreshold: 50,
highDisplayThreshold: '50',
highDisplayThreshold: 1,
highDisplayThreshold: '1',
etc...

```
				...	{
						sensor: "light.bathroom",
						name: "Baño %v% desde %r%",
						displayvalue: false,
						highDisplayThreshold: '50',
						icons: [ ...
```
Can you please guide me?

**Comment by Snille** [comment]
Hm... I realised that the "attributes"  did not work as expected, and in the case of a "light" you need to compare the attribute "brightness" to be able to set a threshold (because "on" and "off" are not numbers). Or you could (if your dimmer/plug/switch) supports it use the "watt" (power reding) to trigger at a specified point...

But, instead I just added an "Equal to" option in the sensors options... So., pull the changes and do this in your conf:
```
values: [{
	sensor: "light.bathroom",
	displayWhenEqualTo: "on",
}]
```
Hope it works. :)

**Comment by estradanet** [comment]
Thank you so much!!!! works perfectly
